free_body_sim/print_ft: false
free_body_sim/frequency: 500
free_body_sim/publish_status: false
free_body_sim/gravity_on: true
free_body_sim/initial_rpy:
  - 0.0
  - 0.0
  - 0.0
free_body_sim/initial_position:
  - 0.0
  - 0.0
  - 0.0
free_body_sim/vicon_pub_freq: 100
free_body_sim/ecb_bandwidth_hz: 15
free_body_sim/vicon_noise_std_exyz:
  - 1.01646014e-05
  - 4.16398263e-06
  - 6.27907061e-06
  - 2.37471348e-04
  - 8.75457449e-04
  - 7.40946226e-05
# free_body_sim/vicon_noise_std_exyz:
#   - 0.0
#   - 0.0
#   - 0.0
#   - 0.0
#   - 0.0
#   - 0.0
free_body_sim/current_noise_std: 0.029008974233986275
free_body_sim_utils/delay_time: 0.001
free_body_sim_utils/delay_repub_freq: 200